/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CadastroCliente;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author tigones
 */
public class Busca extends javax.swing.JFrame {

    /**
     * Creates new form Busca
     */
    public Busca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        opcaoBusca = new javax.swing.JComboBox<>();
        entBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        saidaCodigo = new javax.swing.JTextField();
        saidaNome = new javax.swing.JTextField();
        saidaCPF = new javax.swing.JTextField();
        saidaTelefone = new javax.swing.JTextField();
        saidaLogradouro = new javax.swing.JTextField();
        saidaNumero = new javax.swing.JTextField();
        saidaBairro = new javax.swing.JTextField();
        saidaCidade = new javax.swing.JTextField();
        saidaEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca por Cliente"));

        opcaoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opçoes de Busca", "Codigo", "CPF" }));
        opcaoBusca.setToolTipText("Opções de Buscar");
        opcaoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoBuscaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Logradouro:");

        jLabel5.setText("Bairro:");

        jLabel6.setText("Cidade:");

        jLabel7.setText("Telefone:");

        jLabel8.setText("N*:");

        jLabel9.setText("Estado:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saidaNome))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(saidaCidade)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(saidaLogradouro)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                .addComponent(opcaoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saidaNumero)
                            .addComponent(saidaEstado)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(saidaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saidaTelefone))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saidaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(saidaBairro)))
                        .addGap(12, 12, 12))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(40, 40, 40)
                        .addComponent(btnAlterar)
                        .addGap(261, 261, 261)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcaoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(saidaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(saidaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(saidaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saidaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(saidaLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saidaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(saidaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(saidaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saidaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnLimpar)
                    .addComponent(btnSair)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        

        ativarCampos();
        BuscaDados();
               
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        
        sair();
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        AlterarDados();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void opcaoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoBuscaActionPerformed
        // TODO add your handling code here:
        //Escolhe a Forma (tipo) da Busca
if (opcaoBusca.getSelectedIndex() == 1) {
limpar();
entBusca.enable(true);
 
}
if (opcaoBusca.getSelectedIndex() == 2) {
limpar();
 
} else if (opcaoBusca.getSelectedIndex() == 3) {
BuscaModificada busca = new BuscaModificada();
busca.setVisible(true);
limpar();
}
        
    }//GEN-LAST:event_opcaoBuscaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        ExcluirDados();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busca().setVisible(true);
            }
        });
    }
    
    
public void limpar() {
entBusca.setText("");
saidaCodigo.setText("");
saidaNome.setText("");
saidaCPF.setText("");
saidaTelefone.setText("");
saidaLogradouro.setText("");
saidaNumero.setText("");
saidaBairro.setText("");
saidaCidade.setText("");
saidaEstado.setText("");
}

public static void sair() {
// frame.setVisible(false);
// Comando para fecha Janela.
//frame.dispose();
System.exit(0);
}

//Ativa os campos
public void ativarCampos() {
entBusca.setEnabled(true);
saidaCodigo.setEnabled(true);
saidaNome.setEnabled(true);
saidaCPF.setEnabled(true);
saidaTelefone.setEnabled(true);
saidaLogradouro.setEnabled(true);
saidaNumero.setEnabled(true);
saidaBairro.setEnabled(true);
saidaCidade.setEnabled(true);
saidaEstado.setEnabled(true);
}

//Busca os dados no BD
public void BuscaDados() {
boolean consulta = true;
 
try {
// * Driver conector MySQL.
Class.forName("com.mysql.jdbc.Driver");
 
// * Conexão BD
Connection con = DriverManager.getConnection(
"jdbc:mysql://localhost/BDCadastro", "root", "123456");
 
Statement stmt = con.createStatement();
 
// * Entras de dados no campo codigo do formulário.
int BuscaCodigo = Integer.parseInt(entBusca.getText());
String BuscaCPF = entBusca.getText();
 
ResultSet RS = null;
 
// Escolha a Opção de Busca.
if (opcaoBusca.getSelectedIndex() == 0) {
JOptionPane.showMessageDialog(null,
"Escolha uma Opção de Busca!");
 
} else if (opcaoBusca.getSelectedIndex() == 1) {
RS = stmt
.executeQuery("Select * from TabFicha where Matricula = "
+ BuscaCodigo);
 
while (RS.next()) {
 
// * Exibe os valore retornados na consulta.
 
// * Pega a Matricula.
int Mat = RS.getInt("Matricula");
 
// * Conver inteiro para String
saidaCodigo.setText(String.valueOf(Mat));
 
// Pega os demais.
saidaNome.setText(RS.getString("Nome"));
saidaCPF.setText(RS.getString("CPF"));
saidaTelefone.setText(RS.getString("Telefone"));
saidaLogradouro.setText(RS.getString("Logradouro"));
saidaNumero.setText(RS.getString("Numero"));
saidaBairro.setText(RS.getString("Bairro"));
saidaCidade.setText(RS.getString("Cidade"));
saidaEstado.setText(RS.getString("Estado"));
 
consulta = false;
JOptionPane.showMessageDialog(null, "Dados Encontrado!");
 
}
 
} else if (opcaoBusca.getSelectedIndex() == 2) {
RS = stmt.executeQuery("Select * from TabFicha where CPF = "
+ BuscaCPF);
 
while (RS.next()) {
 
// * Pega o CPF.
String CPF = RS.getString("CPF");
saidaCPF.setText(CPF);
 
// * Exibe os valore retornados na consulta.
saidaNome.setText(RS.getString("Nome"));
saidaCodigo.setText(RS.getString("Matricula"));
saidaTelefone.setText(RS.getString("Telefone"));
saidaLogradouro.setText(RS.getString("Logradouro"));
saidaNumero.setText(RS.getString("Numero"));
saidaBairro.setText(RS.getString("Bairro"));
saidaCidade.setText(RS.getString("Cidade"));
saidaEstado.setText(RS.getString("Estado"));
 
consulta = false;
JOptionPane.showMessageDialog(null, "Dados Encontrado!");
 
}
 
}
 
if (consulta) {
JOptionPane.showMessageDialog(null, "Dados não Encontrados!");
 
}
RS.close();
stmt.close();
 
// * Fecha conexão com DB.
con.close();
 
} catch (SQLException Erro) {
JOptionPane.showMessageDialog(null,
"Erro Cmdo SQL" + Erro.getMessage());
 
} catch (ClassNotFoundException Erro) {
JOptionPane.showMessageDialog(null, "Driver não Encontrado!");
 
}
}


//Altera os dados no BD
public void AlterarDados() {
try {
// * Drive Conector MySQL.
Class.forName("com.mysql.jdbc.Driver");
 
// * Conexão como BD.
Connection con = DriverManager.getConnection(
"jdbc:mysql://localhost/BDCadastro", "root", "123456");
 
// * Objeto comdo SQL.
Statement stmt = con.createStatement();
 
// * Opção de Entrada para Alterar.
int consMatricula = Integer.parseInt(entBusca.getText());
String consCPF = entBusca.getText();
 
// * Pega os dados no formulário.
int cadMat = Integer.parseInt(saidaCodigo.getText());
String cadNome = saidaNome.getText();
String cadCPF = saidaCPF.getText();
String cadTelefone = saidaTelefone.getText();
String cadLogradouro = saidaLogradouro.getText();
int cadNumero = Integer.parseInt(saidaNumero.getText());
String cadBairro = saidaBairro.getText();
String cadCidade = saidaCidade.getText();
String cadEstado = saidaEstado.getText();
 
// Escolha a Opção de Busca.
if (opcaoBusca.getSelectedIndex() == 1) {
int registro = stmt.executeUpdate("update TabFicha set "
+ "Nome='" + cadNome + "',CPF='" + cadCPF
+ "',Telefone='" + cadTelefone + "',Logradouro='"
+ cadLogradouro + "',Numero='" + cadNumero
+ "',Bairro='" + cadBairro + "',Cidade='" + cadCidade
+ "',Estado='" + cadEstado + "', Matricula=" + cadMat
+ " where Matricula=" + consMatricula);
 
if (registro != 0)
JOptionPane.showMessageDialog(null, "Dados Alterados!");
 
else
JOptionPane.showMessageDialog(null, "Dados Não Alterados!");
stmt.close();
 
// * Fecha conexão com BD.
con.close();
 
} else if (opcaoBusca.getSelectedIndex() == 2) {
int registro = stmt.executeUpdate("update TabFicha set "
+ "Matricula='" + cadMat + "',Nome='" + cadNome
+ "',Telefone='" + cadTelefone + "',Logradouro='"
+ cadLogradouro + "',Numero='" + cadNumero
+ "',Bairro='" + cadBairro + "',Cidade='" + cadCidade
+ "',Estado='" + cadEstado + "',CPF=" + cadCPF
+ "where CPF=" + consCPF);
 
if (registro != 0)
JOptionPane.showMessageDialog(null, "Dados Alterados!");
 
else
JOptionPane.showMessageDialog(null, "Dados NãoAlterados!");
stmt.close();
 
// * Fecha conexão com BD.
con.close();
}
 
} catch (SQLException Erro) {
JOptionPane.showMessageDialog(null,
"Erro Cmdo SQL" + Erro.getMessage());
 
} catch (ClassNotFoundException e) {
JOptionPane.showMessageDialog(null, "Driver não encontrado");
}
}

//Exclui dados no BD
public void ExcluirDados() {
try {
// * Drive Conector MySQL.
Class.forName("com.mysql.jdbc.Driver");
 
// * Conexão como BD.
Connection con = DriverManager.getConnection(
"jdbc:mysql://localhost/BDCadastro", "root", "123456");
 
// * Objeto comdo SQL.
Statement stmt = con.createStatement();
 
int excluirMatricula = Integer.parseInt(entBusca.getText());
int registro = stmt
.executeUpdate("delete from TabFicha where Matricula="
+ excluirMatricula);
 
if (registro != 0) {
JOptionPane.showMessageDialog(null, "Dados Excluídos!");
limpar();
 
} else {
JOptionPane.showMessageDialog(null, "Dados não Excluídos!");
}
stmt.close();
 
// * Limpar a caixa de Texto.
limpar();
 
// * Fecha conexão com o BD.
con.close();
 
} catch (SQLException Erro) {
JOptionPane.showMessageDialog(null,
"Erro Cmdo SQL" + Erro.getMessage());
 
} catch (ClassNotFoundException Erro) {
JOptionPane.showMessageDialog(null, "Driver não Encontrado!");
 
}
}








    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel contentPane;
    private javax.swing.JTextField entBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> opcaoBusca;
    private javax.swing.JTextField saidaBairro;
    private javax.swing.JTextField saidaCPF;
    private javax.swing.JTextField saidaCidade;
    private javax.swing.JTextField saidaCodigo;
    private javax.swing.JTextField saidaEstado;
    private javax.swing.JTextField saidaLogradouro;
    private javax.swing.JTextField saidaNome;
    private javax.swing.JTextField saidaNumero;
    private javax.swing.JTextField saidaTelefone;
    // End of variables declaration//GEN-END:variables

    
    private static class opcaoBusca {

        private static int getSelectedIndex() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public opcaoBusca() {
        }
    }

    private static class BuscaModificada {

        public BuscaModificada() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
